CREATE TABLE watch_dirs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path TEXT NOT NULL UNIQUE,
    extensions TEXT NOT NULL DEFAULT '',
    recursive INTEGER NOT NULL DEFAULT 1,
    enabled INTEGER NOT NULL DEFAULT 1,
    stable_wait_ms INTEGER NOT NULL DEFAULT 2000,
    archive_after_import INTEGER NOT NULL DEFAULT 0,
    archive_path TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
